export type GameState =
  | 'PRE_SHOW' | 'INTRO' | 'QUESTION_READY' | 'QUESTION_LIVE' | 'ANSWER_LOCKED'
  | 'LIFELINE_ACTIVE' | 'REVEAL' | 'KNOWLEDGE_DROP' | 'SCORE_COMMITTED'
  | 'NEXT_QUESTION' | 'FINAL' | 'COMPLETE';

export const TRANSITIONS: Record<GameState, GameState[]> = {
  PRE_SHOW: ['INTRO'],
  INTRO: ['QUESTION_READY'],
  QUESTION_READY: ['QUESTION_LIVE'],
  QUESTION_LIVE: ['ANSWER_LOCKED', 'LIFELINE_ACTIVE'],
  LIFELINE_ACTIVE: ['QUESTION_LIVE', 'ANSWER_LOCKED'],
  ANSWER_LOCKED: ['REVEAL'],
  REVEAL: ['KNOWLEDGE_DROP', 'SCORE_COMMITTED'],
  KNOWLEDGE_DROP: ['SCORE_COMMITTED'],
  SCORE_COMMITTED: ['NEXT_QUESTION', 'FINAL'],
  NEXT_QUESTION: ['QUESTION_READY'],
  FINAL: ['COMPLETE'],
  COMPLETE: [],
};

export const canTransition = (from: GameState, to: GameState): boolean =>
  TRANSITIONS[from].includes(to);
